# Generated by Django 4.1 on 2023-05-25 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="seat", unique_together=set(),),
    ]
