# Generated by Django 4.1.7 on 2023-05-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_ticket_customer_remove_ticket_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
