# Generated by Django 4.1.7 on 2023-05-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_ticket_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passenger",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="passenger",
            name="phone_number",
            field=models.CharField(max_length=15),
        ),
    ]
